import { RISK_ORDER, QUANTUM_ORDER } from './colors'

/**
 * Parse a CycloneDX v1.7 CBOM JSON produced by cbom-scan.
 * Throws if the format is invalid.
 */
export function parseReport(raw) {
  if (!raw || raw.bomFormat !== 'CycloneDX') {
    throw new Error(
      'Not a valid CycloneDX file. Expected bomFormat: "CycloneDX".'
    )
  }
  if (!Array.isArray(raw.components) || raw.components.length === 0) {
    throw new Error(
      'No components found in this CycloneDX report. Make sure it was generated by cbom-scan.'
    )
  }

  const getProps = (component) => {
    const map = {}
    for (const p of component.properties || []) map[p.name] = p.value
    return map
  }

  const findings = raw.components.map((c, idx) => {
    const p = getProps(c)
    return {
      uid:          idx,
      id:           p['cbom:ruleId']      || '',
      algorithm:    c.name               || '',
      language:     p['cbom:language']    || '',
      category:     p['cbom:category']    || '',
      quantumImpact:p['cbom:quantumImpact']|| '',
      riskLevel:    p['cbom:riskLevel']   || '',
      file:         p['cbom:file']        || '',
      line:         parseInt(p['cbom:line']) || 0,
      snippet:      p['cbom:snippet']     || '',
      oid:          p['cbom:oid']         || null,
      notes:        c.description         || '',
      bomRef:       c['bom-ref']          || '',
    }
  })

  return {
    projectName: raw.metadata?.component?.name || 'Unknown Project',
    timestamp:   raw.metadata?.timestamp       || '',
    toolVersion: raw.metadata?.tools?.[0]?.version || '-',
    specVersion: raw.specVersion               || '',
    serialNumber:raw.serialNumber              || '',
    findings,
  }
}

/** Aggregate counts by risk, quantum, language, category + quantum risk score. */
export function computeStats(findings) {
  const byRisk = {}, byQuantum = {}, byLanguage = {}, byCategory = {}

  for (const f of findings) {
    byRisk[f.riskLevel]       = (byRisk[f.riskLevel]       || 0) + 1
    byQuantum[f.quantumImpact]= (byQuantum[f.quantumImpact]|| 0) + 1
    byLanguage[f.language]    = (byLanguage[f.language]    || 0) + 1
    byCategory[f.category]    = (byCategory[f.category]    || 0) + 1
  }

  const total  = findings.length
  const shor   = byQuantum['shor_breakable']  || 0
  const grover = byQuantum['grover_weakened'] || 0
  const weak   = byQuantum['already_weak']    || 0

  const quantumScore = total > 0
    ? Math.round((shor * 1.0 + grover * 0.6 + weak * 0.3) / total * 100)
    : 0

  return { byRisk, byQuantum, byLanguage, byCategory, quantumScore, total }
}

/** Top N files sorted by (critical DESC, high DESC, total DESC). */
export function topRiskyFiles(findings, n = 10) {
  const map = {}
  for (const f of findings) {
    if (!map[f.file]) {
      map[f.file] = { file: f.file, critical: 0, high: 0, medium: 0, low: 0, info: 0, total: 0, maxRisk: 'info' }
    }
    map[f.file][f.riskLevel]++
    map[f.file].total++
    const cur  = RISK_ORDER.indexOf(map[f.file].maxRisk)
    const next = RISK_ORDER.indexOf(f.riskLevel)
    if (next < cur) map[f.file].maxRisk = f.riskLevel
  }
  return Object.values(map)
    .sort((a, b) => b.critical - a.critical || b.high - a.high || b.total - a.total)
    .slice(0, n)
}

/** Build a nested tree structure from flat file paths. */
export function buildFileTree(findings) {
  const tree = {}
  for (const f of findings) {
    const parts = f.file.replace(/\\/g, '/').split('/')
    let node = tree
    for (let i = 0; i < parts.length - 1; i++) {
      if (!node[parts[i]]) node[parts[i]] = { __isDir: true, __children: {} }
      node = node[parts[i]].__children
    }
    const fname = parts[parts.length - 1]
    if (!node[fname]) node[fname] = { __isDir: false, __findings: [] }
    node[fname].__findings.push(f)
  }
  return tree
}

/** Return the worst risk level from a list of findings. */
export function getMaxRisk(findings) {
  let best = 'info'
  for (const f of findings) {
    if (RISK_ORDER.indexOf(f.riskLevel) < RISK_ORDER.indexOf(best)) best = f.riskLevel
  }
  return best
}
